version: "3.8"

services:
  # --- FRONTEND BUILD STAGE ---
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: uptime-client-prod
    networks:
      - mynet

  # --- BACKEND API ---
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: uptime-api-prod
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=uptime
      - DB_USER=postgres
      - DB_PASS=postgres
    networks:
      - mynet

  # --- DATABASE ---
  postgres:
    image: postgres:15
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/default.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - client
      - backend
    networks:
      - mynet

volumes:
  pgdata:

networks:
  mynet:
