version: "3.8"

services:
  api:
    container_name: uptime-api-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    depends_on:
      - postgres

  client:
    container_name: uptime-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env

  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
