version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - api

  client:
    container_name: uptime-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod

  api:
    container_name: uptime-api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    expose:
      - "3001"
    env_file:
      - ./api/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-prod
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
